name: bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'patch,minor,major'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - run: npm version ${{ github.event.inputs.version }}
    - run: git push origin master
    - run: git push --tags
